### ISSUE TITLE
JSON.parse error occur during request converting

### ISSUE THREAD

**Issue by seungjae87** [caihuiji/node-highcharts-exporting#2]
```
SyntaxError: Unable to parse JSON string
  at IncomingMessage.<anonymous> (/Users/a0ly/dev/internal-admin/node_modules/node-highcharts-exporting/index.js:94:26)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:913:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickDomainCallback (node.js:397:17)
```

I encountered such error when I call exporting method.

``` javascript
var converter = require('node-highcharts-exporting');

converter({
  type:'png',
  options:{
    chart:{
      type:'line'
    },
    title:{
      text: '한글제목'  // this part occurs parsing error
    },
   yAxis: {
      title: {
         text:'subtitle'
      }
   },
  data:{
    xAxis:{
     categories:['x1', 'x2', 'x3']
   },
   series:[{
      name:'a', data:[1,2,1]
   }]
  }
}, function(error, result){
// handle the result
});
```

However, If I pass english value, the problem is not occurred.
In some case, I need to pass the value which is not english, such as korean.

**Comment by caihuiji** [comment]
fix
